import type { KnowledgeItem, Author } from './types';

export const MOCK_AUTHORS: Author[] = [
  {
    id: 'author-1',
    name: 'BGrowth Editorial',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop',
    role: 'Chief Knowledge Officer',
    type: 'Internal',
    bio: 'BGrowth editorial team curating business education for service entrepreneurs.',
    socialLinks: { linkedin: 'https://linkedin.com', website: 'https://bgrowthclub.com' },
  },
  {
    id: 'author-2',
    name: 'AI Content Engine',
    avatar: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=100&auto=format&fit=crop',
    role: 'AI Content Generator',
    type: 'AI Generated',
    bio: 'BGrowth AI-powered content generation system.',
    socialLinks: {},
  },
];

export const MOCK_ITEMS: KnowledgeItem[] = [
  {
    id: 'ki-001',
    title: 'How to Start a Mobile Notary Business in 2026',
    slug: 'how-to-start-mobile-notary-business-2026',
    excerpt: 'A complete step-by-step guide to launching your mobile notary business, from getting commissioned to finding your first clients.',
    featuredImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop',
    contentType: 'Guide',
    category: 'Notary',
    industry: 'Notary',
    language: 'en',
    difficulty: 'Beginner',
    readingTime: '8 min read',
    tags: ['Notary', 'Business Launch', 'SOP', 'Mobile Business'],
    authorId: 'author-1',
    lastUpdated: '2026-07-14',
    seo: {
      title: 'How to Start a Mobile Notary Business in 2026 | BGrowth',
      metaDescription: 'Complete guide to launching a mobile notary business — commission, tools, pricing, and first clients.',
      canonicalUrl: 'https://bgrowthclub.com/knowledge/mobile-notary-business',
      ogImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1200',
      schemaType: 'HowTo',
      index: true,
      follow: true,
    },
    blocks: [
      { id: 'b1', type: 'paragraph', data: { text: 'Starting a mobile notary business is one of the fastest paths to self-employment in the service industry.' } },
      { id: 'b2', type: 'heading', data: { text: 'Step 1: Get Your Notary Commission', level: 2 } },
      { id: 'b3', type: 'paragraph', data: { text: 'Each state has different requirements. Research your state\'s notary application process and fees.' } },
      { id: 'b4', type: 'callout', data: { type: 'info', title: 'Pro Tip', text: 'Apply for your E&O insurance at the same time as your commission to save time.' } },
      { id: 'b5', type: 'heading', data: { text: 'Step 2: Set Up Your Business', level: 2 } },
      { id: 'b6', type: 'paragraph', data: { text: 'Register your business, open a business bank account, and set up your scheduling system.' } },
      { id: 'b7', type: 'cta', data: { type: 'Download Free Checklist', title: 'Get the Notary Business Launch Checklist', description: 'Download the complete checklist used by top-earning mobile notaries.', buttonText: 'Download Free', linkUrl: '#' } },
    ],
    attachments: [
      { id: 'att-1', name: 'Notary_Business_Launch_Checklist.pdf', size: '1.2 MB', type: 'PDF', url: '#' },
    ],
    relatedContent: [
      { id: 'rc-1', title: 'Notary Appointment Workspace™', type: 'Product', url: '#' },
      { id: 'rc-2', title: 'How to Price Your Notary Services', type: 'Article', url: '#' },
    ],
    featuredOptions: {
      featured: true,
      featuredOnHomepage: true,
      featuredOnCategory: true,
      trending: true,
      editorsPick: false,
    },
    publishing: {
      slug: 'how-to-start-mobile-notary-business-2026',
      status: 'Published',
      visibility: 'Public',
      publishDate: '2026-07-14',
      scheduleDate: '',
      futureWebsiteUrl: 'https://bgrowthclub.com/knowledge/mobile-notary-business',
      publicationNotes: 'Featured on homepage for July.',
    },
  },
  {
    id: 'ki-002',
    title: 'Cleaning Business Pricing Guide: How to Charge for Every Job',
    slug: 'cleaning-business-pricing-guide',
    excerpt: 'Learn how to price residential and commercial cleaning jobs to maximize profit without losing clients.',
    featuredImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop',
    contentType: 'Article',
    category: 'Cleaning',
    industry: 'Cleaning',
    language: 'en',
    difficulty: 'Intermediate',
    readingTime: '6 min read',
    tags: ['Cleaning', 'Pricing', 'Business Growth'],
    authorId: 'author-1',
    lastUpdated: '2026-07-12',
    seo: {
      title: 'Cleaning Business Pricing Guide 2026 | BGrowth',
      metaDescription: 'How to price cleaning jobs correctly — hourly vs flat rate, overhead, and profit margins.',
      canonicalUrl: 'https://bgrowthclub.com/knowledge/cleaning-pricing-guide',
      ogImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200',
      schemaType: 'Article',
      index: true,
      follow: true,
    },
    blocks: [
      { id: 'b1', type: 'paragraph', data: { text: 'Pricing is one of the biggest challenges for cleaning business owners. Too low and you lose money. Too high and you lose clients.' } },
      { id: 'b2', type: 'heading', data: { text: 'Hourly vs Flat Rate Pricing', level: 2 } },
      { id: 'b3', type: 'comparison', data: { headers: ['Method', 'Pros', 'Cons'], rows: [['Hourly', 'Flexible, fair for complex jobs', 'Clients may feel uncertain'], ['Flat Rate', 'Clear expectations, easier to sell', 'Risk of underestimating time']] } },
    ],
    attachments: [],
    relatedContent: [
      { id: 'rc-1', title: 'Cleaning Appointment Workspace™', type: 'Product', url: '#' },
    ],
    featuredOptions: {
      featured: false,
      featuredOnHomepage: false,
      featuredOnCategory: true,
      trending: false,
      editorsPick: true,
    },
    publishing: {
      slug: 'cleaning-business-pricing-guide',
      status: 'Published',
      visibility: 'Public',
      publishDate: '2026-07-12',
      scheduleDate: '',
      futureWebsiteUrl: 'https://bgrowthclub.com/knowledge/cleaning-pricing-guide',
      publicationNotes: '',
    },
  },
  {
    id: 'ki-003',
    title: 'BGrowth Studio Release Notes — July 2026',
    slug: 'bgrowth-studio-release-notes-july-2026',
    excerpt: 'New features, bug fixes, and improvements shipped in the July 2026 release of BGrowth Studio.',
    featuredImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop',
    contentType: 'Release Notes',
    category: 'Technology',
    industry: 'Technology',
    language: 'en',
    difficulty: 'Beginner',
    readingTime: '3 min read',
    tags: ['Release Notes', 'BGrowth Studio', 'Updates'],
    authorId: 'author-2',
    lastUpdated: '2026-07-15',
    seo: {
      title: 'BGrowth Studio Release Notes July 2026',
      metaDescription: 'See what\'s new in BGrowth Studio — new builders, bug fixes, and performance improvements.',
      canonicalUrl: 'https://bgrowthclub.com/knowledge/release-notes-july-2026',
      ogImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200',
      schemaType: 'Article',
      index: true,
      follow: true,
    },
    blocks: [
      { id: 'b1', type: 'heading', data: { text: 'New Features', level: 2 } },
      { id: 'b2', type: 'checklist', data: { title: 'Released in July 2026', items: [{ text: 'Knowledge Engine module' }, { text: 'Product Engine with SEO and Commerce tabs' }, { text: 'GZIP compression for large templates' }, { text: 'PDF download improvements' }] } },
      { id: 'b3', type: 'heading', data: { text: 'Bug Fixes', level: 2 } },
      { id: 'b4', type: 'paragraph', data: { text: 'Fixed save issues with large checklist templates. Fixed PDF blank page issue. Fixed GAS proxy timeout.' } },
    ],
    attachments: [],
    relatedContent: [],
    featuredOptions: {
      featured: false,
      featuredOnHomepage: false,
      featuredOnCategory: false,
      trending: false,
      editorsPick: false,
    },
    publishing: {
      slug: 'bgrowth-studio-release-notes-july-2026',
      status: 'Draft',
      visibility: 'Public',
      publishDate: '',
      scheduleDate: '2026-07-20',
      futureWebsiteUrl: '',
      publicationNotes: 'Schedule for July 20.',
    },
  },
];

export const CATEGORIES = [
  'Business', 'Technology', 'Finance', 'Cleaning', 'Notary',
  'Taxes', 'Bookkeeping', 'Marketing', 'Legal', 'Real Estate',
];

export const INDUSTRIES = [
  'Cleaning', 'Notary', 'Tax', 'Bookkeeping', 'Construction',
  'Healthcare', 'Photography', 'Landscaping', 'Restaurant', 'Real Estate',
];

export const TAGS = [
  'License', 'Invoice', 'Appointment', 'Stripe', 'Google',
  'Marketing', 'Pricing', 'CRM', 'Customer', 'SOP', 'Compliance',
];
